export const DIALOGS_SET_ITEMS = 'DIALOGS:SET_ITEMS';
export const DIALOGS_SET_CURRENT_DIALOG_ID = 'DIALOGS:SET_CURRENT_DIALOG_ID';
export const DIALOGS_SET_LOADING = 'DIALOGS:SET_LOADING';

export const MESSAGES_SET_ITEMS = 'MESSAGES:SET_ITEMS';
export const MESSAGES_SET_IS_LOADING = 'MESSAGES:SET_IS_LOADING';
export const MESSAGES_ADD_MESSAGE = 'MESSAGES:ADD_MESSAGE';

export const USER_SET_DATA = 'USER:SET_DATA';
export const USER_SET_IS_AUTH = "USER:SET_IS_AUTH";
